plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

def facePPPropertiesFile = project.file("facepp.properties")
def facePPProperties = new Properties()
if (facePPPropertiesFile.exists()) {
    facePPProperties.load(new FileInputStream((facePPPropertiesFile)))
} else  {
    facePPProperties.setProperty("FACE_API_KEY", "")
    facePPProperties.setProperty("FACE_API_SECRET", "")
}

android {
    namespace 'com.tgwgroup.facecomparelib'
    compileSdk 35

    defaultConfig {
        minSdk 26

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        buildConfigField "String", "FACE_API_KEY", "\"${facePPProperties.getProperty("FACE_API_KEY")}\""
        buildConfigField "String", "FACE_API_SECRET", "\"${facePPProperties.getProperty("FACE_API_SECRET")}\""
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.okhttp
    implementation libs.okhttp.logging.interceptor
    implementation project(':baselib')
}